sudo: false
language: ruby
rvm:
  - 2.3.3
  - 2.4.2
  - 2.5.0
before_install: gem install bundler
script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
bundler_args: --without development
cache: bundler
addons:
  code_climate:
    repo_token: 7752db32522c9674f3fd7a2b56fef7e202900ef8c2602104250678eb44d1a164
